ForestSpiderNest:
  originalPrefabName: Spawner_GreydwarfNest
  newSpawnerName: ForestSpiderNest
  HoverText: 'Spider den'
  spawnRadius: 2
  nearRadius: 30
  farRadius: 200
  triggerDistance: 80
  levelUpChance: 30
  maxNear: 3
  maxTotal: 10
  spawnTimer: 0
  spawnIntervalSeconds: 20
  spawnOnGroundOnly: true
  setPatrolSpawnPoint: true
  sizeScaleFactor: 0.5
  spawns:
  - prefabName: ForestSpider
    minLevel: 1
    maxLevel: 3
    weight: 3
  spawnerHealth: 150
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: Resistant
    mChop: Normal
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Immune
    mPoison: Immune
    mSpirit: Ignore
