MeadowsSpiderNest:
  originalPrefabName: Spawner_GreydwarfNest
  hoverText: 'Spider den'
  spawnRadius: 2
  nearRadius: 30
  farRadius: 200
  triggerDistance: 80
  levelUpChance: 15
  maxNear: 2
  maxTotal: 5
  spawnTimer: 0
  spawnIntervalSeconds: 20
  spawnOnGroundOnly: true
  setPatrolSpawnPoint: true
  sizeScaleFactor: 0.3
  spawns:
  - prefabName: MeadowsSpider
    minLevel: 0
    maxLevel: 1
    weight: 1
  spawnerHealth: 150
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: VeryResistant
    mChop: Normal
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Immune
    mPoison: Immune
    mSpirit: Ignore
BlackForestSpiderNest:
  originalPrefabName: Spawner_GreydwarfNest
  hoverText: 'Spider den'
  spawnRadius: 2
  nearRadius: 30
  farRadius: 200
  triggerDistance: 80
  levelUpChance: 15
  maxNear: 2
  maxTotal: 5
  spawnTimer: 0
  spawnIntervalSeconds: 20
  spawnOnGroundOnly: true
  setPatrolSpawnPoint: true
  sizeScaleFactor: 0.3
  spawns:
    - prefabName: BlackForestSpider
      minLevel: 0
      maxLevel: 1
      weight: 1
  spawnerHealth: 150
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: VeryResistant
    mChop: Normal
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Immune
    mPoison: Immune
    mSpirit: Ignore
SwampSpiderNest:
  originalPrefabName: Spawner_GreydwarfNest
  hoverText: 'Something is lurking in this den'
  spawnRadius: 2
  nearRadius: 30
  farRadius: 200
  triggerDistance: 80
  levelUpChance: 15
  maxNear: 5
  maxTotal: 20
  spawnTimer: 0
  spawnIntervalSeconds: 7
  spawnOnGroundOnly: true
  setPatrolSpawnPoint: true
  sizeScaleFactor: 0.2
  spawns:
    - prefabName: LurkingSpiderSwamp
      minLevel: 0
      maxLevel: 1
      weight: 1
  spawnerHealth: 250
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: VeryResistant
    mChop: Normal
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Immune
    mPoison: Immune
    mSpirit: Ignore
MountainSpiderNest:
  originalPrefabName: Spawner_GreydwarfNest
  hoverText: 'Spider den covered by snow'
  spawnRadius: 2
  nearRadius: 30
  farRadius: 200
  triggerDistance: 80
  levelUpChance: 15
  maxNear: 2
  maxTotal: 5
  spawnTimer: 0
  spawnIntervalSeconds: 20
  spawnOnGroundOnly: true
  setPatrolSpawnPoint: true
  sizeScaleFactor: 0.3
  spawns:
    - prefabName: SnowSpiderMountain
      minLevel: 0
      maxLevel: 1
      weight: 1
  spawnerHealth: 400
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: VeryResistant
    mChop: Normal
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Immune
    mPoison: Immune
    mSpirit: Ignore
PlainsSpiderNest:
  originalPrefabName: Spawner_GreydwarfNest
  hoverText: 'Spider den'
  spawnRadius: 2
  nearRadius: 30
  farRadius: 200
  triggerDistance: 80
  levelUpChance: 15
  maxNear: 2
  maxTotal: 5
  spawnTimer: 0
  spawnIntervalSeconds: 20
  spawnOnGroundOnly: true
  setPatrolSpawnPoint: true
  sizeScaleFactor: 0.3
  spawns:
    - prefabName: TanSpiderPlains
      minLevel: 0
      maxLevel: 1
      weight: 8
    - prefabName: BrownSpiderPlains
      minLevel: 1
      maxLevel: 2
      weight: 2
  spawnerHealth: 800
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: VeryResistant
    mChop: Normal
    mPickaxe: Ignore
    mFire: Immune
    mFrost: Weak
    mLightning: Immune
    mPoison: Immune
    mSpirit: Ignore
