MeadowsSpider:
  originalPrefabName: TreeSpider
  characterName: 'Spider'
  characterGroup: ''
  faction: ForestMonsters
  health: 50
  characterIsBoss: false
  isTamed: false
  onDefeatSetGlobalKey: ''
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: Normal
    mChop: Ignore
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Normal
    mPoison: Immune
    mSpirit: Immune
  defaultItems:
    - spider_leftattack
    - spider_rightattack
    - spider_jump
    - web_attack
  randomWeapons: []
  randomArmors: []
  randomShields: []
  randomSets: []
BlackForestSpider:
  originalPrefabName: ForestSpider
  characterName: 'Forest Spider'
  characterGroup: spider
  faction: ForestMonsters
  health: 100
  characterIsBoss: false
  isTamed: false
  onDefeatSetGlobalKey: ''
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: Normal
    mChop: Ignore
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Normal
    mPoison: Immune
    mSpirit: Immune
  defaultItems:
    - spider_leftattack
    - spider_rightattack
    - spider_jump
    - web_attack
  randomWeapons: []
  randomArmors: []
  randomShields: []
  randomSets: []
LurkingSpiderSwamp:
  originalPrefabName: BlackSpider
  characterName: 'Lurking Spider'
  characterGroup: spider
  faction: Undead
  health: 40
  characterIsBoss: false
  isTamed: false
  onDefeatSetGlobalKey: ''
  damageModifiers:
    mBlunt: Normal
    mSlash: Normal
    mPierce: Normal
    mChop: Ignore
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Weak
    mLightning: Normal
    mPoison: Immune
    mSpirit: Normal
  defaultItems:
    - small_spider_attack
  randomWeapons: []
  randomArmors: []
  randomShields: []
  randomSets: []
SnowSpiderMountain:
  originalPrefabName: FrigidSpider
  characterName: 'Snow Spider'
  characterGroup: spider
  faction: MountainMonsters
  health: 200
  characterIsBoss: false
  isTamed: false
  onDefeatSetGlobalKey: ''
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: Normal
    mChop: Ignore
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Normal
    mPoison: Immune
    mSpirit: Immune
  defaultItems:
    - spider_leftattack
    - spider_rightattack
    - spider_jump
    - web_attack
  randomWeapons: []
  randomArmors: []
  randomShields: []
  randomSets: []
TanSpiderPlains:
  originalPrefabName: TanSpider
  characterName: 'Tan Spider'
  characterGroup: spider
  faction: PlainsMonsters
  health: 250
  characterIsBoss: false
  isTamed: false
  onDefeatSetGlobalKey: ''
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: Normal
    mChop: Ignore
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Normal
    mPoison: Immune
    mSpirit: Immune
  defaultItems:
    - spider_leftattack
    - spider_rightattack
    - spider_jump
    - web_attack
  randomWeapons: []
  randomArmors: []
  randomShields: []
  randomSets: []
BrownSpiderPlains:
  originalPrefabName: BrownSpider
  characterName: 'Brown Spider'
  characterGroup: spider
  faction: PlainsMonsters
  health: 250
  characterIsBoss: false
  isTamed: false
  onDefeatSetGlobalKey: ''
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: Normal
    mChop: Ignore
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Normal
    mPoison: Immune
    mSpirit: Immune
  defaultItems:
    - spider_leftattack
    - spider_rightattack
    - spider_jump
    - web_attack
  randomWeapons: []
  randomArmors: []
  randomShields: []
  randomSets: []
VenomSpider:
  originalPrefabName: GreenSpider
  characterName: 'Venom Spider'
  characterGroup: spider
  faction: ForestMonsters
  health: 300
  characterIsBoss: false
  isTamed: false
  onDefeatSetGlobalKey: ''
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: Normal
    mChop: Ignore
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Normal
    mPoison: Immune
    mSpirit: Immune
  defaultItems:
    - spider_leftattack
    - spider_rightattack
    - spider_jump
    - web_attack
  randomWeapons: []
  randomArmors: []
  randomShields: []
  randomSets: []
FrozenSpider:
  originalPrefabName: FrostSpider
  characterName: 'Frozen Spider'
  characterGroup: spider
  faction: ForestMonsters
  health: 300
  characterIsBoss: false
  isTamed: false
  onDefeatSetGlobalKey: ''
  damageModifiers:
    mBlunt: Resistant
    mSlash: Normal
    mPierce: Normal
    mChop: Ignore
    mPickaxe: Ignore
    mFire: Weak
    mFrost: Immune
    mLightning: Normal
    mPoison: Immune
    mSpirit: Immune
  defaultItems:
    - spider_leftattack
    - spider_rightattack
    - spider_jump
    - web_attack
  randomWeapons: []
  randomArmors: []
  randomShields: []
  randomSets: []
  